var GAME_LEVELS = [
   
//Level One
   ["                                                                               ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                    o      o                    ",
   "                                                                                ",
   "                                                   xx      xx                   ",
   "                                    o o      xx                                 ",
   "               xxxxxxxx                       x!!!!!!!!!!!!!!!x                 ",
   "               xo                    xxxxx    x!!!!!!!!!!!!!!!x                 ",
   "               xo                             xxxxxxxxxx!xx!xxx             xx  ",
   "  xx           xxxxxxx                                  v  v                 x  ",
   "  x           xx                        o                                    x  ",
   "  x           x                     xxxxxxxxx                              o x  ",
   "  x         xx                                      o                        x  ",
   "  x  @ o    xxxxxxxxxxxxxxxxxxxxxx                                           x  ",
   "  x  xxx  xxxx!!!!!xx!xx!!xxx!xxxx                  xxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x!!!!!!!xxxxxx!xxx!x!x!x!xx!xxxx!!!!!!!!!!!!!!!!!!xxxx!!!!!xxxxx              ",
   "  x!!!!!!!xxxxxx!xx!xxx!!xx!x!xxxx!!!!!!!!!!!!!!!!!!xxxx!!!!!xxxxx              ",
   "  x!!!!!!!xxxxxx!xx!!!!!!xxx!!xxxx!!!!!!!!!!!!!!!!!!xxxx!!!!!!!!!!!!x           ",
   "  x!!!!!!!xxxx!!!!!!xxx!!xxxx!xxxx!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx           ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                "],
  
   //Level Two
  ["                                        					 ",
   "                                        					 ",
   "                                        					 ",
   "                                        					 ",
   "                                         					 ",
   "                                                  			 ",
   "                                                   			 ",
   "                                                 			 ",
   "                                                    		 ",
   "                                                             ",
   "     xxxxxxxxx                                               ",
   "    x!!!!!!!!!x                                              ",
   "   x!!!x!!!x!!!x                       	                     ",
   "   x!x!!!!!!!x!x                                             ",
   "   x!!x!!!!!x!!x                                             ",
   "    xx!!xxx!!xx                                              ",
   "      xx!!!xx                   o                            ",
   "        xxx                    xxx       xxx  x   o          ",
   "                               x  x   o  x  x x              ",
   "                          xx    x   x!x   x   xxx x          ",
   "@                   o         x  x  x!x x  x  x x x          ",
   "xxxxx        xxxxxxxx     x    xxx  xxx  xxx  x x x      x   ",
   "!!!!x     xxxx!!!!!!x     xx                            ox   ",
   "!!!!x        x!!!!!!x     xx              xx   xxxxxxxx  x   ",
   "!!!!x        x!!!!!xx       xxxxxxxxxx    x!!!!!!!xx  !  x   ",
   "!!!!x        x!!!!!x  o                  xxx!!!!!!xx  !!!x   ",
   "!!!!xxxxxxxxxx!!!!!x      x               xx!!!!!!xx         ",
   "!!!!x!!!!!!!!x!!!!!xxxxxxxxxxxxxxxxxxxxxxx!!!!!!xx           ",
   "!!!!x!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx            ",
   "!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx             "],
  
//Level Three
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                           	  ",
   "                                                                                                           	  ",
   "                                                                                        					  ",
   "                                                                                            				  ",
   "                                                                                           					  ",
   "                                                                                    						  ",
   "                                                                                  							  ",
   "                                                                                   							  ",
   "                                                                                           					  ",
   "                                                                        									  ",
   "                                                                                         					  ",
   "                                                                               								  ",
   "                                                                                                      		  ",
   "                                                                              								  ",
   "                                                                             								  ",
   "                                                                    										  ",
   "                                                                											  ",
   "                                                															  ",
   "         x                                              													  ",
   "         x                                                          										  ",
   "         x                                                           										  ",
   "         x            xxxxxxxxx                                                     						  ",
   "    @    x            x!!!!!!!x                                 											  ",
   "  xxx    x            x!!!!!!!!                                                                            x  ",
   "  x      x            x!!!!!!!!!!                                                                          x  ",
   "  x      xxxxxxxxxxxxxxxxvxxxxxxv                                            xxxxx                         x  ",
   "  x                             x                                        x   x                             x  ",
   "  x                           xx                      !!!!          !!!!        x x x                      x  ",
   "  x                                       xxxx       |xvvx|    |xvvx|     xxx                              x  ",
   "  x                                 xxx                                                                    x  ",
   "  x               xxxxx       xxx         x                                    x!!!x          !            x  ",
   "  x                                       x                                     xxx          xxx           x  ",
   "  x             xxxxxxxxxxxx  x           x                                          					   x  ",
   "  x             x!!!!!!!!!!x  x       xxxxx                                         x!!!!!!!!!!!!!x	       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                               xxxxxxxxxxx                                                                    ",
   "                                                                                                              "],
  
//Level FOUR
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
